### ISSUE TITLE
Notification Icon Visual Improvements

### ISSUE THREAD

**Issue by sirito97** [darklinkpower/Stardust#22]
### Feature Description

Current notification indicator looks out of place, improvements for it can be like the screenshot to match other elements, also I think it's better to make the notification icon static (not disappearing when there's no notifications) and what disappears is the notification number (disappears when it is 0)

### Screenshots

old
![unknown](https://user-images.githubusercontent.com/66971290/160654981-cf09e9c4-d34c-4719-94c1-9a9fc457de5e.png)
new
![unknown](https://user-images.githubusercontent.com/66971290/160655038-2290ed47-2e2e-446f-a1fc-20c9d3ee3602.png)
new with 0 notification
![image](https://user-images.githubusercontent.com/66971290/160655153-ea0bfe5e-ae1b-49ce-a400-618ac713cfb0.png)

**Comment by darklinkpower** [comment]
That Old icon is not correct, are you using a custom version or something? Maybe you used ThemeModifier? The icon is purple by default

![image](https://user-images.githubusercontent.com/1389286/160762175-1d5e7d7b-0d4c-4925-bb0c-2f4a07460bf6.png)


Regarding the proposal:
- The issue with the number backround is that the buttons already use the purple color for the background color
![image](https://user-images.githubusercontent.com/1389286/160761830-cddc2fcd-5d14-4062-b7df-3b2aa7290f32.png)

- I'm not sure if I like the idea of having it shown permanently. The area is already pretty limited in PCs with high DPI/Lower resolutions so adding another button probably won't even fit in a lot of PCs. My screenshots are on 1080p 125%  and it will be worse on other PCs.

**Comment by sirito97** [comment]
Strange thing, I remember fresh installing the theme and the notification icon remained same for me.

You are right regarding the limited space I actually hide most of the top bar items.

But I think it will be better for the icon to have the same background as other top panel items, because it really looks odd compared to them.

I wonder if playnite supports moving this notification icon on the sidebar or not, that will be a good thing for the narrow top bar area too.

**Comment by darklinkpower** [comment]
Something definitely caused the color change in your setup. You can verify that it uses the GlyphBrush (Purple color) here https://github.com/darklinkpower/Stardust/blob/master/source/Views/TopPanel.xaml#L139

> But I think it will be better for the icon to have the same background as other top bar items, because it really looks odd compared to them.

I'm still not sure about this, I tried this and was not entirely convinced. The reason is that I think the notification button should look distinct enough to other buttons to make sure that the user notices it. I'll need to try again another time.

> I wonder if playnite supports moving this notification icon on the sidebar or not, that will be a good thing for the narrow top bar area too.

Doing this is not possible and imo it wouldn't look right. There's also the issue again that space is limited.

![image](https://user-images.githubusercontent.com/1389286/160875780-b707c3ca-bc1f-461c-b418-9396f5496365.png)
