### ISSUE TITLE
[Feature Request] Add game installation size to the Details View element bar

### ISSUE THREAD

**Issue by astrobound** [darklinkpower/Stardust#35]
### Feature Description

Alongside the Last Played, Time Played, and Completion Status elements on the bottom of the Game Overview panel, an Install Size  element could be added. See screenshot attached.

### Screenshots

![image](https://user-images.githubusercontent.com/29896740/213953758-8bc2fd39-f5de-426e-a7ed-94f156dd4938.png)

**Comment by darklinkpower** [comment]
I'm afraid that this is difficult because that space is already being used by extensions data: Achievements (SuccessStory extension) and HowLongToBeat. The issue is that no space is remaining and available space is even less with lower resolution screens or with DPI higher than 100% and also if you have extra panels like Filter or Explorer Panel or the Sidebar.

![image](https://user-images.githubusercontent.com/1389286/213977406-976b8541-7f81-4e75-99eb-ed4c53131f0a.png)

**Comment by astrobound** [comment]
Ah good point. I’ll look into writing a simple extension for my needs. Thanks for the feedback!
