### ISSUE TITLE
Weird Gap in Cover images

### ISSUE THREAD

**Issue by yuma-dev** [darklinkpower/Stardust#46]
### Bug Description

After copying the screenshot settings I am getting weird gaps in the Cover Images

### Extensions log

[extensions.log](https://github.com/user-attachments/files/15523760/extensions.log)

### Screenshots

![image](https://github.com/darklinkpower/Stardust/assets/76885566/c668d732-d7a2-450d-bc59-4703fcef6210)

**Comment by darklinkpower** [comment]
The reason is that the covers of those games don't match the aspect ratio you have configured in Settings -> Grid View. You need to download different ones or change the stretch mode here to Uniform to Fill but I don't recommend that.

![image](https://github.com/darklinkpower/Stardust/assets/1389286/33c65a3a-01c3-4082-b058-8aa842d97ab9)
