### ISSUE TITLE
Icons missing in new game details box

### ISSUE THREAD

**Issue by Bolthier** [darklinkpower/Stardust#51]
### Bug Description

In the new game details box the icons for time and completion status are missing for me. They are just shown as boxes indicating missing icons. I tried reinstalling the theme, still the icons are missing.

It doesn't seem to affect all users, as the screenshots in new issues from others are showing the icons.

### To Reproduce

No real steps, just my system info.

Stardust: 2.68

Playnite: 10.34
SDK: 6.11.0
Theme API: 2.6.0

OS: Windows 10 Pro N
OS Version: 22H2

### Screenshots

![Screenshot 2024-09-28 121249](https://github.com/user-attachments/assets/2ef13796-143a-4606-a660-f096deea3f80)

**Comment by darklinkpower** [comment]
The reason is that you system doesn't have the font used in the icons [Segoe Fluent Icons](https://learn.microsoft.com/en-us/windows/apps/design/style/segoe-fluent-icons-font) that is available by default on Windows 11. You can manually install it from here: https://learn.microsoft.com/en-us/windows/apps/design/downloads/#fonts

I'll consider if I should change the icon to prevent this issue on W10 systems.

**Comment by darklinkpower** [comment]
New update available that uses a different font to prevent this issue.
