### ISSUE TITLE
[Feature] More customizability and options in Grid View

### ISSUE THREAD

**Issue by OsoaGH** [darklinkpower/Stardust#9]
**Describe the solution you'd like**
Either a built-in menu that has options or more options in the ThemeModifier addon
Some options that I think would be nice are:

- Using the icons for Last Played, Time Played, Competion Status and HowLongToBeat from Details View in Grid view
- Fold things like links, scores and other small details so they don't take up half the screen with a blank space on the right.
- Option to hide game name (useful if you have Extra Metadata Tools)
- Option to widen the Details Panel in Grid View
- Option to move HowLongToBeat and SuccessStory data to top of the panel or choose a position
- Option to hide Zoom slider

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/33041004/140551036-0800f7cf-7972-492f-b18e-a2b6b715eb2f.png)
Here is a quick and sloppy mock-up I made, hopefully should demonstrate some of the options I presented

**Comment by darklinkpower** [comment]
Changing the details section like how you want is not possible. A complete modification of the theme file definition is needed, so it would need to be a different theme. This could be done if someone created a fork of the theme with this change, similar to the Helium fork someone made. I can't personally work on this due to the amount of time it would require, although be aware that it's likely that if someone makes a fork it won't be up to date with the original theme since I would not be personally maintaining it.
